# -*- coding: utf-8 -*-
"""KH1_Web_Scrapping_SentimentAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gxV2Nuz_LMSGvhpZA9-eAzduHtUa6JFp
"""

from bs4 import BeautifulSoup as bs
import requests

link = 'https://www.amazon.in/product-reviews/B089MVKH71'

page = requests.get(link)

page

soup = bs(page.content, 'html.parser')

print(soup.prettify())

names = soup.find_all('span' , class_ = 'a-profile-name')
names

cust_name = []
for name in names:
  cust_name.append(name.get_text())

cust_name.pop(0)

cust_name.pop(0)

cust_name

title = soup.find_all('a' , class_='review-title-content')
title

review_title = []
for t in title:
  review_title.append(t.get_text().strip('\n'))

review_title

import pandas as pd
df = pd.DataFrame()

df['name'] = cust_name
df['review_title'] = review_title

df

rating = soup.find_all('i' , class_='review-rating')
rating

rate = []
for r in rating:
  rate.append(r.get_text().strip('\n'))

rate.pop(0)

rate.pop(0)

df['ratings'] = rate

df

review = soup.find_all('span' , class_='review-text-content')
review

reviews = []
for r in review:
  reviews.append(r.get_text().strip('\n'))

len(reviews)

df['reviews'] = reviews

df

from textblob import TextBlob

review_sentiments = []
for rev in df.reviews:
  review_sentiments.append(TextBlob(rev).sentiment.polarity)

df['sentiments'] = review_sentiments

df

